name: Build for gts7lwifi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-gts7lwifi:
    uses: ./.github/workflows/build.yml
    with:
      device: gts7lwifi
      device_name: Galaxy Tab S7
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
