name: Build for gts7xl

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-gts7xl:
    uses: ./.github/workflows/build.yml
    with:
      device: gts7xl
      device_name: Galaxy Tab S7 Plus LTE 
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
