name: Build for gts7l

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-gts7l:
    uses: ./.github/workflows/build.yml
    with:
      device: gts7l
      device_name: Galaxy Tab S7 LTE
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
