name: Release builder

on:
  workflow_call:
    inputs:
      device:
        type: string
        required: true
      device_name:
        type: string
        required: true
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true

permissions:
  contents: write

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    env:
      DEVICE: ${{ inputs.device }}
      DEVICE_NAME: ${{ inputs.device_name }}

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set Build Start Time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Run build script
        run: |
          export DEVICE=${{ env.DEVICE }}
          ./build.sh

      - name: Set Build End Time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Build Duration
        run: |
          duration=$((END_TIME - START_TIME))
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          echo "BUILD_DURATION=${minutes}m ${seconds}s" >> $GITHUB_ENV

      - name: Upload to Telegram
        run: |
          gitsha1=$(git rev-parse --short HEAD)
          zip_file=$(ls not-*.zip 2>/dev/null | head -n 1)
          if [ -z "$zip_file" ]; then
            echo "No zip found!"
            exit 1
          fi
          DEVICE_NAME_ESCAPED=$(echo "$DEVICE_NAME" | sed 's/[][_*()~`>#+=|{}.!-]/\\&/g')
          DEVICE_ESCAPED=$(echo "$DEVICE" | sed 's/[][_*()~`>#+=|{}.!-]/\\&/g')
          printf "| Localversion: `cat out/include/config/kernel.release`
           | Build Date: `date +'%d %B %Y'`
           | Build commit hash: $gitsha1
           | KernelSU: yes
           | SELinux: Enforcing" >> buildDetails.txt
          buildDetails="`cat buildDetails.txt`"
          msg="*not\\-kernel* build for the *${DEVICE_NAME_ESCAPED} \\(${DEVICE_ESCAPED}\\)*
          * *
          \`\`\`
          $buildDetails
          \`\`\`
          * * "
          file="$zip_file"
          curl -s -F document=@$file "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -F "disable_web_page_preview=true" \
          -F "parse_mode=markdownv2" \
          -F caption="$msg"

      - name: Set ZIP File Path
        run: |
         zip=$(ls not-CI-*.zip 2>/dev/null | head -n1)
         if [ -z "$zip" ]; then
           echo "❌ No ZIP found!"
           exit 1
         fi
         echo "zip_file=$zip" >> $GITHUB_ENV

      - name: Set release tag
        run: echo "RELEASE_TAG=${DEVICE}-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Prepare Release Info
        run: |
          set -e
          echo "KERNEL_VERSION=$(cat out/include/config/kernel.release)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +'%d %B %Y')" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "CLANG_VERSION=$(${{ github.workspace }}/tc/clang/bin/clang --version | head -n1)" >> $GITHUB_ENV
          KSU_VERSION=$(grep -m1 'KSU_VERSION' -r ./KernelSU/kernel/Makefile | sed -E 's/.*KSU_VERSION=([0-9]+).*/\1/')
          [ -z "$KSU_VERSION" ] && KSU_VERSION="Unknown"
          echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV
          git -C KernelSU fetch --tags 2>/dev/null || true
          KSU_VERSION_STR=$(git -C KernelSU describe --tags --always 2>/dev/null)
          [ -z "$KSU_VERSION_STR" ] && KSU_VERSION_STR="Unknown"
          echo "KSU_VERSION_STR=$KSU_VERSION_STR" >> $GITHUB_ENV
          SUSFS_VERSION=$(grep -m1 'SUSFS_VERSION' ./include/linux/susfs.h 2>/dev/null | awk -F'"' '{print $2}')
          [ -z "$SUSFS_VERSION" ] && SUSFS_VERSION="Unknown"
          echo "SUSFS_VERSION=$SUSFS_VERSION" >> $GITHUB_ENV

      - name: Debug ZIP
        run: ls -lh

      - name: Create Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: not_kernel ${{ env.KERNEL_VERSION }} for ${{ env.DEVICE_NAME }}
          files: ${{ env.zip_file }}
          body: |
             Clang version: ${{ env.CLANG_VERSION }}
             Build Date: ${{ env.BUILD_DATE }}
             KernelSU version: ${{ env.KSU_VERSION }} / ${{ env.KSU_VERSION_STR }}
             SusFS version: ${{ env.SUSFS_VERSION }}
             SELinux: Enforcing
             Commit: ${{ env.COMMIT_HASH }}
             Build completed in: ${{ env.BUILD_DURATION }}
              
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
