name: Build for r8q

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-r8q:
    uses: ./.github/workflows/build.yml
    with:
      device: r8q
      device_name: Galaxy S20 FE
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
